### shows all products
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk3MzAyNzV9.6TAIKhFjDDtevBNTYdLBggUUVmxjAabml5Tytlk8Eqk

### shows one product
GET http://localhost:3000/products/2.json

### creates a product
POST http://localhost:3000/products.json
Content-Type: application/json

{
  "name": "Mouse",
  "price": 30,        
  "image_url": "insert",
  "description": "tool used for navigating a computer" 
}

### updates a product
PATCH http://localhost:3000/products/2.json 
Content-Type: application/json

{
  "name": "Dell Mouse"
}

### deletes a product
DELETE http://localhost:3000/products/4.json

### creates a new user
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Lebron",
  "email": "lebron@test.com",
  "password": "what",
  "password_confirmation": "what"
}

### logs user in for a sessoin
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "pranav@test.com",
  "password": "what"
}

### creates a new order
POST http://localhost:3000/order.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk4MTkxMzl9.THKbYjtHRLumCyL_dDd0ewxvLizppky1YmLZjeLuYt4
Content-Type: application/json

{
  "product_id": 2,
  "quantity": 1,
  "subtotal": 499.00
}

### shows one order
GET http://localhost:3000/order/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk4MTkxMzl9.THKbYjtHRLumCyL_dDd0ewxvLizppky1YmLZjeLuYt4

### shows all orders
GET http://localhost:3000/orders.json