### shows all products
GET http://localhost:3000/products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk3MzAyNzV9.6TAIKhFjDDtevBNTYdLBggUUVmxjAabml5Tytlk8Eqk

### shows one product
GET http://localhost:3000/products/2.json

### creates a product
POST http://localhost:3000/products.json
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk5ODMyOTZ9.RwWdKyYKuCZpoCTXG3zEATLYRrvoKDoIGWlyYZHAb-k

{
  "name": "Xbox",
  "price": 499.00,        
  "image_url": "insert",
  "description": "Microsoft Console",
  "number_items": 15,
  "supplier_id": 2
}

### updates a product
PATCH http://localhost:3000/products/2.json 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk5ODMyOTZ9.RwWdKyYKuCZpoCTXG3zEATLYRrvoKDoIGWlyYZHAb-k

{
  "name": "Dell Mouse"
}

### deletes a product
DELETE http://localhost:3000/products/4.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2ODk5ODMyOTZ9.RwWdKyYKuCZpoCTXG3zEATLYRrvoKDoIGWlyYZHAb-k

### creates a new user
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Lebron",
  "email": "lebron@test.com",
  "password": "what",
  "password_confirmation": "what"
}

### logs user in for a sessoin
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "pranav@test.com",
  "password": "what"
}

### creates a new order
POST http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2OTAzMjcyNjh9.hjz0Qivu_VggFLOfo_cT4xdvBm4C4MEAgCSHSy1Ass4
Content-Type: application/json


### shows one order
GET http://localhost:3000/orders/1.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2OTAzMjgzOTd9.zdYK_7Ni8x1vL0Kaa89dmpqryps2MtyGPFcQPPmWyDs

### shows all orders
GET http://localhost:3000/orders.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2OTAzMjgzOTd9.zdYK_7Ni8x1vL0Kaa89dmpqryps2MtyGPFcQPPmWyDs

### creates carted products
POST http://localhost:3000/carted_products.json 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2OTAzMjgzOTd9.zdYK_7Ni8x1vL0Kaa89dmpqryps2MtyGPFcQPPmWyDs

{
  "product_id": 2,
  "quantity": 1
}

### shows all carted products
GET http://localhost:3000/carted_products.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2OTAzMjgzOTd9.zdYK_7Ni8x1vL0Kaa89dmpqryps2MtyGPFcQPPmWyDs

### delete carted product
DELETE http://localhost:3000/carted_products/6.json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxLCJleHAiOjE2OTAzMjgzOTd9.zdYK_7Ni8x1vL0Kaa89dmpqryps2MtyGPFcQPPmWyDs
