json.id product.id
json.name product.name
json.description product.description
json.price product.price
json.tax product.tax
json.total product.total
json.supplier product.supplier
json.supplier_id product.supplier_id
json.images product.images
